- name: set the Message Of The Day (MOTD)
  become: true
  template:
    src: motd
    dest: "/etc/motd"
    mode: 0644

- name: "Print motd always"
  # Note that this is added at the end of the file, so
  # with the default bashrc by Ubuntu, it's run only interactively
  # moreover, login shells already print it by default
  become: true
  become_user: "{{ qm_customizations_vm_user }}"
  lineinfile:
    path: "${HOME}/.bashrc"
    line: "shopt -q login_shell || cat /etc/motd # Print only in non-login shells"

- name: Improve handling of bash history
  become: true
  become_user: "{{ qm_customizations_vm_user }}"
  lineinfile:
    path: "${HOME}/.bashrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - regexp: HISTCONTROL=
    line: HISTCONTROL=ignoredups
  - regexp: HISTSIZE=
    line: HISTSIZE=100000
  - regexp: HISTFILESIZE=
    line: HISTFILESIZE=100000
