- include_role:
    name: release_notes
  vars:
    section: "{{ qm_customizations_vm_name }}"
    option: "version"
    value: "{{ qm_customizations_vm_version }}"

- name: store Ubuntu version number
  command: lsb_release -sd
  changed_when: false
  register: lsb_release

- include_role:
    name: release_notes
  vars:
    section: "{{ qm_customizations_vm_name }}"
    option: "Operating System"
    value: "{{ lsb_release.stdout }}"

- include_role:
    name: release_notes
  vars:
    section: "{{ qm_customizations_vm_name }}"
    option: "Login credentials"
    value: "{{ qm_customizations_vm_user }} / {{ qm_customizations_vm_password }}"
