- name: Converge
  hosts: all

  pre_tasks:
  - name: Update apt cache.
    become: true
    apt:
      update_cache: true
      cache_valid_time: 600
    when: ansible_os_family|lower == 'debian'

  vars:
    run_tests: true
    cloud_platform: docker
    qm_customizations_headless: true

  roles:
  - role: marvel-nccr.quantum_mobile_customizations
